force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Applicable_For__c.field-meta.xml
<CustomField>
    <fullName>Applicable_For__c</fullName>
    <label>Applicable For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Course_Image__c.field-meta.xml
<CustomField>
    <fullName>Course_Image__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Course Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Course_Source__c.field-meta.xml
<CustomField>
    <fullName>Course_Source__c</fullName>
    <label>Course Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Udemy</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>eBook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Course_URL__c.field-meta.xml
<CustomField>
    <fullName>Course_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Course URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/training.cls
public class training
{

    @AuraEnabled  
    public static list<Training__c> getTrainings(string trainingType){
        system.debug('****trainingType'+trainingType);
        list<Training__c> tlist;
          if(string.isBlank(trainingType) || trainingType=='All'){
           tlist =[SELECT ID,Course_Image__c,Course_Name__c,Course_Source__c,
                                          Course_Type__c,Description__c,Status__c,Applicable_for__c,
                                          Course_URL__c
                                     FROM Training__c
                                     Where Status__c='Active'
                                     order by createdDate ASC
                                     ];
           system.debug('tlist'+tlist);
          }
          else{
               tlist =[SELECT ID,Course_Image__c,Course_Name__c,Course_Source__c,
                                          Course_Type__c,Description__c,Status__c,Applicable_for__c,
                                          Course_URL__c
                                     FROM Training__c
                                     Where Status__c='Active'
                                     AND Applicable_for__c INCLUDES (:trainingType)
                                     order by createdDate ASC
                                     ];
           system.debug('tlist'+tlist);
          }
  
        return tlist;
      }
}